language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.6.0
env:
  global:
  - secure: Db6cKzQRDKXN9WQhq4/0ys3EWOnlhfwmplmcr1zZUh4BkT+ULHT58oI6TnzkGyQAsB/qVdgGLbbaacZbekODdPmRLagmaYSbcDzT/fcIfqiTN7BIWLZM15CZBIX8JLd+dHCG5wcAYeEwhd2CbRNxhIF6Cw+lSjYZpZk+FqTs81EyRJIxQrdfhgj93O2fp7GKhAq/8d8A2VUjOcsqJJG+Q/ALNfjEveT+l29JHyz2oi+4xxsfV7h1m2lYrsDpQ1gF36G/5WhJaiiZqMeN1kS4CRH1YuAd+5Gv2n44+3Pewq4UdzJPOp8wKr/QpBOsny9N/bywiAuSXLuukF9doi2lEvoKWX7RSgdwUrC6m+URvtHxhAo3ait+2f8QExKi7I069hap5PaKgY49l5Udpsq+fFmqXljXTkFuiTpf7iQxzjBnS4shuoDMsGqIMOm5tjDz3m2FGGrbqUvcdRqaxQXj/lM94+hP2qtmIO52emNLHj1GmZhu+0EQZCme//CxBKoRUxApJoniqsiR7Hq3ctHRNcN1aImvFYCz/iXQchBZdJqCuDhyTlKX1rrJggi5n3YUilAwyYBxjx7prNClUWcmZsVEyX5dH2FUobWujWeo3CsiHVuHM7Bb2fn7l2rBGPvlEjcI8/4PqhkBnYarHQe5GjEiYlHmYdX0Z1zvHnduoKw=
