language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.6.0
env:
  global:
    secure: B1Rr1Uyk9fzwuWpo9HVI/Jnm6hnzaSXpQ9Bmaegw3fxpaFCtqVliZ9KDqWKF6aq88OnGwe6ii9AKwq2sKVdSDh4vUz8tm+4wlozIpljUReVdFbRNGDmKR7NxcuiIGFWfWExKVWV73OCHt9tWVINbcIXdhGqaViVSvna4T1vgojQWwjwOea0gYIFQZRIi2eWmKK3bVnN5PYEQ0ikwapoErAHcbtRJQrYnxZMsdG50xhsdiMwa3IUMCP7vdb9eY9hy52QU2qR480gSXHM7oV9iSh9nGpSYZu/JHhV61b0B3UnoRmJ4e9GC/Wiy6SxDo9ok1N4ckB2PY9397IFx04GVDGKek8O2eLXK/uPyuYVieHnYpPrVC4kf2kxNzsTMonRIOmzXZSKH2Ur8YAyxOwLwFR/hsaSLdiVu+ZYEhIa0/f02gSuA/iohfu4SwUxIJ4TuW6U1oNxPpDsH1Rq0OCncy3OvQD1AMG7WVn5XDO+hLic/du/l7sprzOs+ZRbxT9sxAQ/Ev9tDvmMbrpGPDxKNnaEGehJvNyqtgagislKgGCrYh3oyO3n98HHV27puRjaCq85qvAiAoK0hz4RbY29Lqny5FmEvMlBDICiPHoQRG4YWmB4DgJYD9XoTCuIfJ+ke2fNnuYKgeu+/n4PrXqQr7VyzmGd/huTP2CoQZ0x0lgs=
