language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.6.0
env:
  global:
    secure: TZlPffV4SrESff6dDhSsU+0MlX5vngqO49TIvW3BuXes6NdeoMw+KOkFlHn8rf2GPVdjZFPzWViui+sW7X7Z0+wUPi36fVKyiRhdoG0DSuBtZN/aTMsidGtzhdW8O57F8cjT5QoX/VcVReMXMLBaKIgLC67yYfQv86BrbGOA0+5aza9K8YLtYXwJLDPCggZr3n8k4iel0oPXFYqieA16lvMDO5GEz5OYMIzPmGcKb8XDOYLkArz8H1QqBzpiVnPmS1MxZ0XnqWrnW0pjEA88u7HMGozlqeiZ4C7/Pl/sHXyGKP27PB+GQ9CYxvp3rW194ssOYXN7TLScjv9s3jWzceWX46nBKol6DyXDoxIRdGjhgDiV1dzoBLBbSf5CQjk0d/miDT7W5XODdpbo7grPi8vOagE2MhjW6vVxVlA2goWNpw/lhsqjmh+62Fh9Wd4qhRq7lxGQ6hWjrJlrpEwNTOS83Qkug8tLDFXuv8ln0k8LQ+Vsekt2NSgTeYiGzszKnHPGL3rS+Hhuzq4/84gSwfzfipDjNtl+0svXjN+nUHgZPyu0c33Hh0sT0IFz4v57G43ca4nN2VWbx8gfl2lsUGYE7Xc2aiQsdjqW+tQcqBut6WZAkqvLxU2XC5Ht1STqlXER2c240tfY25RmAVEUr+B7z8B0gHft8OTMrrStMcE=
