language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.6.0
env:
  global:
    secure: P803B2Kk/XPVB4AyDAfQtB4E1MckHAXKjg8zE96Oo/bM8NNz0CQLs8JAribA8byJGaffuhRkHoQatE72aaeXRKlQydTJdHvLg8xZpGw7c0xcZTIeiBGgCKQYNDRX7iKaX9TzCWQEdoQ0DeyDOZaLz5uHCdHURM+4LwPfcoCdGVw6ZpwvDRpUezLxXthwMZQrSbPFQiirZuyUo+ODZMonuYHBN4VMNDS+c4F5vRTnEj+LcGwe13TAHTo3tWOsm1f8bVG3H+045T+QnO6zF7FDCCONFof6VcO/+26+wIfc4MzNZ0IlToC4Znx7XgsjtJIYq0xsVs83ocyzf0ecjDcSkny4m5BAYYjDtEODKRl4kKUamC2WcW5LA0hcdP4ThUZf6U3SwNLAGipKLvPdOC8N2hJ6oZ+QRx66YmaPDLQFFHauziWzKFGn4WRidjNQZvoMWkjRXhGQIEu718fMUct1ADpS5K3vnYm50hH1OvttJONOSFZZiPKlgBCjQVWmomaJOE/qqgeVKgPDX+NyPKS6rv/y4ibvdKRovawqpvNX5KulliAyJK7BAGxDBXd+5FpOO0Aieyv1N5rEywcBtfP9PXSogw4cSY4ZybGKNJz7vv8ZBd657I/W2EyfaVOxu2P8N7na+SCqucCvNeAK8Jiqox80cYY0eTfbUUoHiCJx9eQ=
