language: ruby
before_script:
- chmod +x "./build.sh"
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.6.0
env:
  global:
    secure: pCN9IBtVAwo7xY83ploe+xfkggcBXQifaf/JSElA6Z+fMfnckGiLlPxcuYE9NS73if/wcXGPgXamvtXt+88PwRQo2FJRkZIA8S+WKsd7gWN3uzmdWFFREGinnDCF+T3zemCeW/I9vIH1b3DezwqJEjZmUE5181MrBS2QOSLIgVqL+Z/8zEttSUWOLggRrlwvByuPMgCUhZGktmbDrHdB8/NWFq2/PXuNMYHCg0xumN+mvqhhhiiqd5Vp8nWDIxSJlhX3ZNks+6ouIHE/k8QIdX2cMYU07OwNO+N9bsom9UTOAY6lvLiELki+/989+5O5GNguCnocLAZUPf4bGMy6HPGXPJMUqwoV2xMXdVB2lprJIzn4gfbdAXi5NTlrSmb5D8G2m7TNOEfZfWLxwVrm/R6O6RsNSzwmv4voSOGtC0lrbMpkkKVqCCwypywxjuCxh688/2+1biUmzax885VRNHCi943Rsnh6Q8h+8GfIkOZo9n2O4Pkv4KLsOCDqsP70HIK95gTLD+l+w7dfgnWk2EtLO28udZa5nHDAyg5QHa9tDubH+15diP1wc1o3tvYDj9kI0CZzk3AZKkK1ui7lI19tQ0t8FAnARauCkjWjT7/xs2SLCD0eeHOIevUpHYD7JTfBmTMUutlNu+0/BGOmjjCjvoptFALPOC4o1xV3V0A=
